services:
    app:
        build: .
        ports:
            - "3000:8080"
        container_name: api-wilayah-ri
        restart: on-failure
        env_file:
            -   .env.docker
        depends_on:
          - db
    db:
        image: postgres:16
        container_name: api-wilayah-ri-db
        restart: on-failure
        ports:
            - "5440:5432"
        environment:
            - POSTGRES_USER=micro
            - POSTGRES_PASSWORD=micro
            - POSTGRES_DB=micro
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata: {}