services:
    app:
        build: .
        ports:
            - "3000:3000"
        container_name: api-wilayah-ri
        restart: on-failure
        depends_on:
          - db
    db:
        image: postgres
        container_name: api-wilayah-ri-db
        restart: on-failure
        ports:
            - "5440:5432"
        environment:
            - POSTGRES_USER=micro
            - POSTGRES_PASSWORD=micro
            - POSTGRES_DB=micro